###############
#             #
# RSB V 0.0.1 #
#             #
###############

island:
  create:

    # BLOKADA CZASOWA NA KOMENDE TWORZENIA WYSPY (MINUTY)
    cooldown: 10

  # PVP NA WYSPACH (TRUE/FALSE | WLACZONE/WYLACZONE)
  pvp: true